### ISSUE TITLE
Fail to repeat the accuracy of the pretrained VGG model

### ISSUE THREAD

**Issue by xhzhao** [VT-vision-lab/VQA_LSTM_CNN#27]
I download the pretrained mode here: https://filebox.ece.vt.edu/~jiasenlu/codeRelease/vqaRelease/train_val/pretrained_lstm_train-val_test

and the corresponding features here:
https://filebox.ece.vt.edu/~jiasenlu/codeRelease/vqaRelease/train_val/data_train-val_test.zip

There is no error when i run eval.lua.
After i put the result files to here: https://github.com/VT-vision-lab/VQA 
I came across the following error:

"
loading VQA annotations and questions into memory...
0:00:07.128280
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "vqaEvalDemo.py", line 31, in <module>
    vqaRes = vqa.loadRes(resFile, quesFile)
  File "../../VQA/PythonHelperTools/vqaTools/vqa.py", line 165, in loadRes
    'Results do not correspond to current VQA set. Either the results do not have predictions for all question ids in annotation file or there is atleast one question id that does not belong to the question ids in the annotation file.'
AssertionError: Results do not correspond to current VQA set. Either the results do not have predictions for all question ids in annotation file or there is atleast one question id that does not belong to the question ids in the annotation file.
"

**Comment by ghost** [comment]
you may make an error in filename.  your resut file in "../data/results" need the same as the filename in "../../VQA/PythonHelperTools/vqaTools/vqa.py" file.  eg: "OpenEnded_mscoco_val2014_fake_results.json"

**Comment by ramonsilvanet** [comment]
I had same problem, but all files names are correct
